$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(282a36ff)
$bg1        = rgba(21222cff)
$bg2        = rgba(343746ff)
$bg3        = rgba(44475aff)
$bg4        = rgba(6272a4ff)

# Foregrounds
$fg         = rgba(f8f8f2ff)
$fg2        = rgba(bfbfbfff)
$fg3        = rgba(6272a4ff)

# Named colors
$red        = rgba(ff5555ff)
$orange     = rgba(ffb86cff)
$yellow     = rgba(f1fa8cff)
$green      = rgba(50fa7bff)
$cyan       = rgba(8be9fdff)
$blue       = rgba(6272a4ff)
$purple     = rgba(bd93f9ff)

# Accents
$accent     = rgba(bd93f9ff)
$accent2    = rgba(ff79c6ff)
$accent3    = rgba(8be9fdff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
