[palettes.colors]
color1 = '#bd93f9'
color2 = '#282a36'
color3 = '#bfbfbf'
color4 = '#343746'
color5 = '#282a36'
color6 = '#21222c'
color7 = '#21222c'
color8 = '#bd93f9'
color9 = '#8be9fd'
color_error = '#ff5555'
