set -gq @thm_bg                    "#282a36"
set -gq @thm_status_bg             "#21222c"
set -gq @thm_active_bg             "#343746"
set -gq @thm_fg                    "#bfbfbf"
set -gq @thm_fg_bright             "#f8f8f2"
set -gq @thm_active_fg             "#f8f8f2"
set -gq @thm_accent                "#bd93f9"
set -gq @thm_border                "#44475a"
set -gq @thm_prefix_bg             "#ffb86c"
set -gq @thm_prefix_fg             "#f8f8f2"
set -gq @thm_copy_fg               "#8be9fd"
set -gq @thm_zoom_fg               "#ff79c6"
