$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(2e3440ff)
$bg1        = rgba(242933ff)
$bg2        = rgba(3b4252ff)
$bg3        = rgba(434c5eff)
$bg4        = rgba(4c566aff)

# Foregrounds
$fg         = rgba(eceff4ff)
$fg2        = rgba(d8dee9ff)
$fg3        = rgba(e5e9f0ff)

# Named colors
$red        = rgba(bf616aff)
$orange     = rgba(d08770ff)
$yellow     = rgba(ebcb8bff)
$green      = rgba(a3be8cff)
$cyan       = rgba(8fbcbbff)
$blue       = rgba(81a1c1ff)
$purple     = rgba(b48eadff)

# Accents
$accent     = rgba(81a1c1ff)
$accent2    = rgba(88c0d0ff)
$accent3    = rgba(b48eadff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
