set -gq @thm_bg                    "#2e3440"
set -gq @thm_status_bg             "#242933"
set -gq @thm_active_bg             "#3b4252"
set -gq @thm_fg                    "#d8dee9"
set -gq @thm_fg_bright             "#eceff4"
set -gq @thm_active_fg             "#eceff4"
set -gq @thm_accent                "#81a1c1"
set -gq @thm_border                "#434c5e"
set -gq @thm_prefix_bg             "#d08770"
set -gq @thm_prefix_fg             "#eceff4"
set -gq @thm_copy_fg               "#b48ead"
set -gq @thm_zoom_fg               "#88c0d0"
