$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(1a1b26ff)
$bg1        = rgba(16161eff)
$bg2        = rgba(292e42ff)
$bg3        = rgba(3b4261ff)
$bg4        = rgba(545c7eff)

# Foregrounds
$fg         = rgba(c0caf5ff)
$fg2        = rgba(a9b1d6ff)
$fg3        = rgba(9aa5ceff)

# Named colors
$red        = rgba(f7768eff)
$orange     = rgba(ff9e64ff)
$yellow     = rgba(e0af68ff)
$green      = rgba(9ece6aff)
$cyan       = rgba(73dacaff)
$blue       = rgba(7aa2f7ff)
$purple     = rgba(bb9af7ff)

# Accents
$accent     = rgba(7aa2f7ff)
$accent2    = rgba(7dcfffff)
$accent3    = rgba(bb9af7ff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
