[palettes.colors]
color1 = '#7aa2f7'
color2 = '#1a1b26'
color3 = '#a9b1d6'
color4 = '#292e42'
color5 = '#1a1b26'
color6 = '#16161e'
color7 = '#16161e'
color8 = '#7aa2f7'
color9 = '#bb9af7'
color_error = '#f7768e'
