[palettes.colors]
color1 = '#c4a7e7'
color2 = '#16141f'
color3 = '#908caa'
color4 = '#1f1d2e'
color5 = '#16141f'
color6 = '#12111a'
color7 = '#12111a'
color8 = '#c4a7e7'
color9 = '#f6c177'
color_error = '#eb6f92'
