set -gq @thm_bg                    "#16141f"
set -gq @thm_status_bg             "#12111a"
set -gq @thm_active_bg             "#1f1d2e"
set -gq @thm_fg                    "#908caa"
set -gq @thm_fg_bright             "#e0def4"
set -gq @thm_active_fg             "#e0def4"
set -gq @thm_accent                "#c4a7e7"
set -gq @thm_border                "#2a2837"
set -gq @thm_prefix_bg             "#c4a7e7"
set -gq @thm_prefix_fg             "#e0def4"
set -gq @thm_copy_fg               "#f6c177"
set -gq @thm_zoom_fg               "#9ccfd8"
