[palettes.colors]
color1 = '#8ab4f8'
color2 = '#101010'
color3 = '#b5b5b5'
color4 = '#202020'
color5 = '#101010'
color6 = '#151515'
color7 = '#151515'
color8 = '#8ab4f8'
color9 = '#cba6f7'
color_error = '#f38ba8'
