set -gq @thm_bg                    "#101010"
set -gq @thm_status_bg             "#151515"
set -gq @thm_active_bg             "#202020"
set -gq @thm_fg                    "#b5b5b5"
set -gq @thm_fg_bright             "#e6e6e6"
set -gq @thm_active_fg             "#e6e6e6"
set -gq @thm_accent                "#8ab4f8"
set -gq @thm_border                "#2a2a2a"
set -gq @thm_prefix_bg             "#fab387"
set -gq @thm_prefix_fg             "#e6e6e6"
set -gq @thm_copy_fg               "#cba6f7"
set -gq @thm_zoom_fg               "#89dceb"
