#!/usr/bin/env python3
"""Generate theme palette files for all 10 themes."""

import json
import os

THEMES_DIR = os.path.dirname(os.path.abspath(__file__))


def rgba(hex6):
    """Convert #rrggbb or rrggbb to rgba(rrggbbff)"""
    h = hex6.lstrip("#")
    return f"rgba({h}ff)"


def hex_(h):
    return "#" + h.lstrip("#")


# Each theme: name -> color slots
# Slots: bg bg1 bg2 bg3 bg4 fg fg2 accent1 accent2 accent3 error source
THEMES = {
    "gruvbox-dark": {
        "bg": "1d2021",
        "bg1": "282828",
        "bg2": "3c3836",
        "bg3": "504945",
        "bg4": "665c54",
        "fg": "ebdbb2",
        "fg2": "a89984",
        "fg3": "928374",
        "accent1": "d79921",
        "accent2": "98971a",
        "accent3": "689d6a",
        "error": "cc241d",
        "source": "d65d0e",
        "red": "cc241d",
        "orange": "d65d0e",
    },
    "rose-pine": {
        "bg": "191724",
        "bg1": "1f1d2e",
        "bg2": "26233a",
        "bg3": "6e6a86",
        "bg4": "9893a5",
        "fg": "e0def4",
        "fg2": "908caa",
        "fg3": "6e6a86",
        "accent1": "f6c177",
        "accent2": "9ccfd8",
        "accent3": "c4a7e7",
        "error": "eb6f92",
        "source": "f6c177",
        "red": "eb6f92",
        "orange": "f6c177",
    },
    "catppuccin-mocha": {
        "bg": "1e1e2e",
        "bg1": "181825",
        "bg2": "313244",
        "bg3": "45475a",
        "bg4": "585b70",
        "fg": "cdd6f4",
        "fg2": "bac2de",
        "fg3": "a6adc8",
        "accent1": "b4befe",
        "accent2": "89b4fa",
        "accent3": "cba6f7",
        "error": "f38ba8",
        "source": "cba6f7",
        "red": "f38ba8",
        "orange": "fab387",
    },
    "tokyo-night": {
        "bg": "1a1b26",
        "bg1": "16161e",
        "bg2": "292e42",
        "bg3": "3b4261",
        "bg4": "545c7e",
        "fg": "c0caf5",
        "fg2": "a9b1d6",
        "fg3": "9aa5ce",
        "accent1": "7aa2f7",
        "accent2": "7dcfff",
        "accent3": "bb9af7",
        "error": "f7768e",
        "source": "7aa2f7",
        "red": "f7768e",
        "orange": "ff9e64",
    },
    "nord": {
        "bg": "2e3440",
        "bg1": "242933",
        "bg2": "3b4252",
        "bg3": "434c5e",
        "bg4": "4c566a",
        "fg": "eceff4",
        "fg2": "d8dee9",
        "fg3": "e5e9f0",
        "accent1": "81a1c1",
        "accent2": "88c0d0",
        "accent3": "b48ead",
        "error": "bf616a",
        "source": "5e81ac",
        "red": "bf616a",
        "orange": "d08770",
    },
    "dracula": {
        "bg": "282a36",
        "bg1": "21222c",
        "bg2": "343746",
        "bg3": "44475a",
        "bg4": "6272a4",
        "fg": "f8f8f2",
        "fg2": "bfbfbf",
        "fg3": "6272a4",
        "accent1": "bd93f9",
        "accent2": "ff79c6",
        "accent3": "8be9fd",
        "error": "ff5555",
        "source": "bd93f9",
        "red": "ff5555",
        "orange": "ffb86c",
    },
    "kanagawa": {
        "bg": "1f1f28",
        "bg1": "16161d",
        "bg2": "2a2a37",
        "bg3": "363646",
        "bg4": "54546d",
        "fg": "dcd7ba",
        "fg2": "c8c093",
        "fg3": "727169",
        "accent1": "7e9cd8",
        "accent2": "76946a",
        "accent3": "d27e99",
        "error": "c34043",
        "source": "7e9cd8",
        "red": "c34043",
        "orange": "ffa066",
    },
    "everforest": {
        "bg": "2d353b",
        "bg1": "272e33",
        "bg2": "3d484d",
        "bg3": "475258",
        "bg4": "56635f",
        "fg": "d3c6aa",
        "fg2": "9da9a0",
        "fg3": "7a8478",
        "accent1": "a7c080",
        "accent2": "7fbbb3",
        "accent3": "d699b6",
        "error": "e67e80",
        "source": "a7c080",
        "red": "e67e80",
        "orange": "e69875",
    },
    "one-dark": {
        "bg": "282c34",
        "bg1": "21252b",
        "bg2": "3e4451",
        "bg3": "545862",
        "bg4": "676f7d",
        "fg": "abb2bf",
        "fg2": "828997",
        "fg3": "5c6370",
        "accent1": "61afef",
        "accent2": "56b6c2",
        "accent3": "c678dd",
        "error": "e06c75",
        "source": "61afef",
        "red": "e06c75",
        "orange": "d19a66",
    },
    "nightfox": {
        "bg": "192330",
        "bg1": "131a24",
        "bg2": "212e3f",
        "bg3": "29394f",
        "bg4": "39506d",
        "fg": "cdcecf",
        "fg2": "738091",
        "fg3": "526175",
        "accent1": "82aaff",
        "accent2": "86e1fc",
        "accent3": "c099ff",
        "error": "c94f6d",
        "source": "82aaff",
        "red": "c94f6d",
        "orange": "f4a261",
    },
    "tomorrow-night": {
        "bg": "1d1f21",
        "bg1": "161719",
        "bg2": "282a2e",
        "bg3": "373b41",
        "bg4": "4b5056",
        "fg": "c5c8c6",
        "fg2": "b4b7b4",
        "fg3": "969896",
        "accent1": "81a2be",
        "accent2": "8abeb7",
        "accent3": "b294bb",
        "error": "cc6666",
        "source": "81a2be",
        "red": "cc6666",
        "orange": "de935f",
    },
    "rose-pine-moon": {
        "bg": "232136",
        "bg1": "1f1d2e",
        "bg2": "2a273f",
        "bg3": "393552",
        "bg4": "6e6a86",
        "fg": "e0def4",
        "fg2": "908caa",
        "fg3": "6e6a86",
        "accent1": "c4a7e7",
        "accent2": "9ccfd8",
        "accent3": "ea9a97",
        "error": "eb6f92",
        "source": "c4a7e7",
        "red": "eb6f92",
        "orange": "f6c177",
    },
    "catppuccin-frappe": {
        "bg": "303446",
        "bg1": "292c3c",
        "bg2": "414559",
        "bg3": "51576d",
        "bg4": "626880",
        "fg": "c6d0f5",
        "fg2": "b5bfe2",
        "fg3": "a5adce",
        "accent1": "8caaee",
        "accent2": "99d1db",
        "accent3": "ca9ee6",
        "error": "e78284",
        "source": "8caaee",
        "red": "e78284",
        "orange": "ef9f76",
    },
    "material-ocean": {
        "bg": "0f111a",
        "bg1": "090b10",
        "bg2": "1f2233",
        "bg3": "2a2e42",
        "bg4": "3b4261",
        "fg": "a6accd",
        "fg2": "828bb8",
        "fg3": "5c6783",
        "accent1": "82aaff",
        "accent2": "89ddff",
        "accent3": "c792ea",
        "error": "f07178",
        "source": "82aaff",
        "red": "f07178",
        "orange": "f78c6c",
    },
    "github-dark": {
        "bg": "0d1117",
        "bg1": "010409",
        "bg2": "161b22",
        "bg3": "21262d",
        "bg4": "30363d",
        "fg": "c9d1d9",
        "fg2": "8b949e",
        "fg3": "6e7681",
        "accent1": "58a6ff",
        "accent2": "79c0ff",
        "accent3": "d2a8ff",
        "error": "f85149",
        "source": "58a6ff",
        "red": "f85149",
        "orange": "db6d28",
    },
    "ayu-dark": {
        "bg": "0f1419",
        "bg1": "0b0e14",
        "bg2": "1b2733",
        "bg3": "253340",
        "bg4": "364a5e",
        "fg": "bfbdb6",
        "fg2": "98958e",
        "fg3": "6c7380",
        "accent1": "39bae6",
        "accent2": "95e6cb",
        "accent3": "d2a6ff",
        "error": "f07178",
        "source": "39bae6",
        "red": "f07178",
        "orange": "ffb454",
    },
    "oxocarbon": {
        "bg": "161616",
        "bg1": "0f0f0f",
        "bg2": "262626",
        "bg3": "393939",
        "bg4": "525252",
        "fg": "dde1e6",
        "fg2": "a2a9b0",
        "fg3": "697077",
        "accent1": "78a9ff",
        "accent2": "08bdba",
        "accent3": "be95ff",
        "error": "ff7eb6",
        "source": "78a9ff",
        "red": "ff7eb6",
        "orange": "ffb784",
    },
    "poimandres": {
        "bg": "1b1e28",
        "bg1": "171922",
        "bg2": "303340",
        "bg3": "4b5263",
        "bg4": "767c9d",
        "fg": "e4f0fb",
        "fg2": "a6accd",
        "fg3": "767c9d",
        "accent1": "89ddff",
        "accent2": "5de4c7",
        "accent3": "fcc5e9",
        "error": "d0679d",
        "source": "89ddff",
        "red": "d0679d",
        "orange": "fffac2",
    },
    "onedark-deep": {
        "bg": "1a212e",
        "bg1": "141922",
        "bg2": "2c313c",
        "bg3": "3b4048",
        "bg4": "4b5263",
        "fg": "abb2bf",
        "fg2": "7f848e",
        "fg3": "5c6370",
        "accent1": "61afef",
        "accent2": "56b6c2",
        "accent3": "c678dd",
        "error": "e06c75",
        "source": "61afef",
        "red": "e06c75",
        "orange": "d19a66",
    },
    "melange": {
        "bg": "292522",
        "bg1": "1f1b18",
        "bg2": "34302c",
        "bg3": "4a443e",
        "bg4": "5a524c",
        "fg": "ece1d7",
        "fg2": "c1a78e",
        "fg3": "867462",
        "accent1": "a98a78",
        "accent2": "78997a",
        "accent3": "7b91b2",
        "error": "d47766",
        "source": "7b91b2",
        "red": "d47766",
        "orange": "e49b5d",
    },
    "gruvbox-dark-hard": {
        "bg": "1d2021",
        "bg1": "1b1b1b",
        "bg2": "282828",
        "bg3": "3c3836",
        "bg4": "504945",
        "fg": "ebdbb2",
        "fg2": "d5c4a1",
        "fg3": "a89984",
        "accent1": "fabd2f",
        "accent2": "b8bb26",
        "accent3": "83a598",
        "error": "fb4934",
        "source": "fe8019",
        "red": "fb4934",
        "orange": "fe8019",
    },
    "gruvbox-dark-soft": {
        "bg": "32302f",
        "bg1": "282828",
        "bg2": "3c3836",
        "bg3": "504945",
        "bg4": "665c54",
        "fg": "ebdbb2",
        "fg2": "d5c4a1",
        "fg3": "bdae93",
        "accent1": "d79921",
        "accent2": "98971a",
        "accent3": "458588",
        "error": "cc241d",
        "source": "d65d0e",
        "red": "cc241d",
        "orange": "d65d0e",
    },
    "noir": {
        "bg": "101010",
        "bg1": "151515",
        "bg2": "202020",
        "bg3": "2a2a2a",
        "bg4": "3a3a3a",
        "fg": "e6e6e6",
        "fg2": "b5b5b5",
        "fg3": "7a7a7a",
        "accent1": "8ab4f8",
        "accent2": "89dceb",
        "accent3": "cba6f7",
        "error": "f38ba8",
        "source": "8ab4f8",
        "red": "f38ba8",
        "orange": "fab387",
    },
}


def make_hyprland(t):
    c = THEMES[t]
    lines = [
        "$font                   = SF Pro Display",
        "$font_bold              = SF Pro Display Bold",
        "$clock_font             = PP Neue Machina Plain Ultrabold",
        "",
        f"$background             = {rgba(c['bg'])}",
        f"$on_background          = {rgba(c['fg'])}",
        "",
        f"$primary                = {rgba(c['accent1'])}",
        f"$on_primary             = {rgba(c['bg'])}",
        f"$primary_container      = {rgba(c['bg3'])}",
        f"$on_primary_container   = {rgba(c['accent1'])}",
        f"$primary_fixed          = {rgba(c['accent1'])}",
        f"$primary_fixed_dim      = {rgba(c['accent1'])}",
        f"$inverse_primary        = {rgba(c['bg3'])}",
        "",
        f"$secondary              = {rgba(c['accent2'])}",
        f"$on_secondary           = {rgba(c['bg'])}",
        f"$secondary_container    = {rgba(c['bg2'])}",
        f"$on_secondary_container = {rgba(c['accent2'])}",
        f"$secondary_fixed        = {rgba(c['accent2'])}",
        f"$secondary_fixed_dim    = {rgba(c['accent2'])}",
        "",
        f"$tertiary               = {rgba(c['accent3'])}",
        f"$on_tertiary            = {rgba(c['bg'])}",
        f"$tertiary_container     = {rgba(c['bg3'])}",
        f"$on_tertiary_container  = {rgba(c['accent3'])}",
        f"$tertiary_fixed         = {rgba(c['accent3'])}",
        f"$tertiary_fixed_dim     = {rgba(c['accent3'])}",
        "",
        f"$error                  = {rgba(c['error'])}",
        f"$on_error               = {rgba(c['bg'])}",
        f"$error_container        = {rgba(c['bg2'])}",
        f"$on_error_container     = {rgba(c['error'])}",
        "",
        f"$surface                = {rgba(c['bg1'])}",
        f"$on_surface             = {rgba(c['fg'])}",
        f"$surface_variant        = {rgba(c['bg3'])}",
        f"$on_surface_variant     = {rgba(c['fg2'])}",
        f"$surface_bright         = {rgba(c['bg2'])}",
        f"$surface_dim            = {rgba(c['bg'])}",
        f"$surface_tint           = {rgba(c['accent1'])}",
        f"$surface_container_lowest  = {rgba(c['bg1'])}",
        f"$surface_container_low     = {rgba(c['bg1'])}",
        f"$surface_container         = {rgba(c['bg2'])}",
        f"$surface_container_high    = {rgba(c['bg3'])}",
        f"$surface_container_highest = {rgba(c['bg4'])}",
        "",
        f"$inverse_on_surface     = {rgba(c['bg'])}",
        f"$inverse_surface        = {rgba(c['fg'])}",
        "",
        f"$outline                = {rgba(c['fg3'])}",
        f"$outline_variant        = {rgba(c['bg3'])}",
        "",
        "$scrim                  = rgba(000000ff)",
        "$shadow                 = rgba(000000ff)",
        "",
        f"$source_color           = {rgba(c['source'])}",
        "",
        "# Extended palette vars",
        f"$on_primary_fixed            = {rgba(c['bg'])}",
        f"$on_primary_fixed_variant    = {rgba(c['bg3'])}",
        f"$on_secondary_fixed          = {rgba(c['bg'])}",
        f"$on_secondary_fixed_variant  = {rgba(c['bg3'])}",
        f"$on_tertiary_fixed           = {rgba(c['bg'])}",
        f"$on_tertiary_fixed_variant   = {rgba(c['bg3'])}",
    ]
    return "\n".join(lines)


def make_ghostty(t):
    c = THEMES[t]
    # 16 terminal colors: black dark-red dark-green dark-yellow dark-blue dark-magenta dark-cyan dark-white
    # and bright versions
    lines = [
        f"background = #{c['bg']}",
        f"foreground = #{c['fg']}",
        f"cursor-color = #{c['accent1']}",
        f"cursor-text = #{c['bg']}",
        f"selection-background = #{c['bg2']}",
        f"selection-foreground = #{c['fg']}",
        "",
        "# Normal colors (0-7)",
        f"palette = 0=#{c['bg1']}",
        f"palette = 1=#{c['error']}",
        f"palette = 2=#{c['accent2']}",
        f"palette = 3=#{c['accent1']}",
        f"palette = 4=#{c['source']}",
        f"palette = 5=#{c['accent3']}",
        f"palette = 6=#{c['accent2']}",
        f"palette = 7=#{c['fg2']}",
        "",
        "# Bright colors (8-15)",
        f"palette = 8=#{c['fg3']}",
        f"palette = 9=#{c['error']}",
        f"palette = 10=#{c['accent2']}",
        f"palette = 11=#{c['accent1']}",
        f"palette = 12=#{c['source']}",
        f"palette = 13=#{c['accent3']}",
        f"palette = 14=#{c['accent2']}",
        f"palette = 15=#{c['fg']}",
    ]
    return "\n".join(lines)


def make_css(t):
    """CSS for waybar, swaync, wlogout — same format as matugen.css"""
    c = THEMES[t]
    lines = [
        "/*",
        f" * CSS Colors — {t}",
        " */",
        "",
        f"@define-color background {hex_(c['bg'])};",
        f"@define-color on_background {hex_(c['fg'])};",
        "",
        f"@define-color primary {hex_(c['accent1'])};",
        f"@define-color on_primary {hex_(c['bg'])};",
        f"@define-color primary_container {hex_(c['bg3'])};",
        f"@define-color on_primary_container {hex_(c['accent1'])};",
        "",
        f"@define-color secondary {hex_(c['accent2'])};",
        f"@define-color on_secondary {hex_(c['bg'])};",
        f"@define-color secondary_container {hex_(c['bg2'])};",
        f"@define-color on_secondary_container {hex_(c['accent2'])};",
        "",
        f"@define-color tertiary {hex_(c['accent3'])};",
        f"@define-color on_tertiary {hex_(c['bg'])};",
        f"@define-color tertiary_container {hex_(c['bg3'])};",
        f"@define-color on_tertiary_container {hex_(c['accent3'])};",
        "",
        f"@define-color error {hex_(c['error'])};",
        f"@define-color on_error {hex_(c['bg'])};",
        f"@define-color error_container {hex_(c['bg2'])};",
        f"@define-color on_error_container {hex_(c['error'])};",
        "",
        f"@define-color surface {hex_(c['bg1'])};",
        f"@define-color on_surface {hex_(c['fg'])};",
        f"@define-color surface_variant {hex_(c['bg3'])};",
        f"@define-color on_surface_variant {hex_(c['fg2'])};",
        f"@define-color surface_bright {hex_(c['bg2'])};",
        f"@define-color surface_dim {hex_(c['bg'])};",
        f"@define-color surface_container {hex_(c['bg2'])};",
        f"@define-color surface_container_low {hex_(c['bg1'])};",
        f"@define-color surface_container_lowest {hex_(c['bg1'])};",
        f"@define-color surface_container_high {hex_(c['bg3'])};",
        f"@define-color surface_container_highest {hex_(c['bg4'])};",
        "",
        f"@define-color outline {hex_(c['fg3'])};",
        f"@define-color outline_variant {hex_(c['bg3'])};",
        "",
        f"@define-color inverse_surface {hex_(c['fg'])};",
        f"@define-color inverse_on_surface {hex_(c['bg'])};",
        f"@define-color inverse_primary {hex_(c['bg3'])};",
        "",
        f"@define-color source_color {hex_(c['source'])};",
        "",
        "/* Aliases used by some components */",
        f"@define-color foreground {hex_(c['fg'])};",
        f"@define-color accent {hex_(c['accent1'])};",
    ]
    return "\n".join(lines)


def make_gtk_css(t):
    c = THEMES[t]
    lines = [
        "/*",
        f" * GTK Colors — {t}",
        " */",
        "",
        f"@define-color accent_color {hex_(c['accent1'])};",
        f"@define-color accent_fg_color {hex_(c['bg'])};",
        f"@define-color accent_bg_color {hex_(c['accent1'])};",
        f"@define-color window_bg_color {hex_(c['bg'])};",
        f"@define-color window_fg_color {hex_(c['fg'])};",
        f"@define-color headerbar_bg_color {hex_(c['bg'])};",
        f"@define-color headerbar_fg_color {hex_(c['fg'])};",
        f"@define-color popover_bg_color {hex_(c['bg1'])};",
        f"@define-color popover_fg_color {hex_(c['fg'])};",
        f"@define-color view_bg_color {hex_(c['bg1'])};",
        f"@define-color view_fg_color {hex_(c['fg'])};",
        f"@define-color card_bg_color {hex_(c['bg1'])};",
        f"@define-color card_fg_color {hex_(c['fg'])};",
        "@define-color sidebar_bg_color @window_bg_color;",
        "@define-color sidebar_fg_color @window_fg_color;",
        "@define-color sidebar_border_color @window_bg_color;",
        "@define-color sidebar_backdrop_color @window_bg_color;",
        f"@define-color thumbnail_bg_color {hex_(c['bg2'])};",
        f"@define-color thumbnail_fg_color {hex_(c['fg'])};",
        f"@define-color dialog_bg_color {hex_(c['bg1'])};",
        f"@define-color dialog_fg_color {hex_(c['fg'])};",
        f"@define-color warning_bg_color {hex_(c['orange'])};",
        f"@define-color warning_fg_color {hex_(c['bg'])};",
        f"@define-color error_bg_color {hex_(c['error'])};",
        f"@define-color error_fg_color {hex_(c['bg'])};",
        f"@define-color success_bg_color {hex_(c['accent2'])};",
        f"@define-color success_fg_color {hex_(c['bg'])};",
        f"@define-color destructive_action_bg_color {hex_(c['error'])};",
        f"@define-color destructive_action_fg_color {hex_(c['bg'])};",
    ]
    return "\n".join(lines)


def make_rofi(t):
    c = THEMES[t]
    return f"""* {{
    background:      rgba({int(c["bg"][0:2], 16)}, {int(c["bg"][2:4], 16)}, {int(c["bg"][4:6], 16)}, 0.85);
    background-alt:  #{c["bg2"]};
    foreground:      #{c["fg"]};
    selected:        #{c["accent1"]};
    active:          #{c["accent2"]};
    urgent:          #{c["error"]};
}}"""


def make_tmux(t):
    c = THEMES[t]
    lines = [
        f'set -gq @thm_bg                    "#{c["bg"]}"',
        f'set -gq @thm_status_bg             "#{c["bg1"]}"',
        f'set -gq @thm_active_bg             "#{c["bg2"]}"',
        f'set -gq @thm_fg                    "#{c["fg2"]}"',
        f'set -gq @thm_fg_bright             "#{c["fg"]}"',
        f'set -gq @thm_active_fg             "#{c["fg"]}"',
        f'set -gq @thm_accent                "#{c["accent1"]}"',
        f'set -gq @thm_border                "#{c["bg3"]}"',
        f'set -gq @thm_prefix_bg             "#{c["source"]}"',
        f'set -gq @thm_prefix_fg             "#{c["fg"]}"',
        f'set -gq @thm_copy_fg               "#{c["accent3"]}"',
        f'set -gq @thm_zoom_fg               "#{c["accent2"]}"',
    ]
    return "\n".join(lines)


def make_opencode(t):
    c = THEMES[t]
    data = {
        "$schema": "https://opencode.ai/theme.json",
        "defs": {
            "primary": hex_(c["accent1"]),
            "on_primary": hex_(c["bg"]),
            "secondary": hex_(c["accent2"]),
            "on_secondary": hex_(c["bg"]),
            "surface": hex_(c["bg"]),
            "on_surface": hex_(c["fg"]),
            "surface_variant": hex_(c["bg3"]),
            "on_surface_variant": hex_(c["fg2"]),
            "background": hex_(c["bg"]),
            "on_background": hex_(c["fg"]),
            "error": hex_(c["error"]),
            "on_error": hex_(c["bg"]),
            "outline": hex_(c["fg3"]),
            "outline_variant": hex_(c["bg3"]),
        },
        "theme": {
            "primary": {"dark": "primary", "light": "primary"},
            "secondary": {"dark": "secondary", "light": "secondary"},
            "accent": {"dark": "primary", "light": "primary"},
            "error": {"dark": "error", "light": "error"},
            "warning": {"dark": "secondary", "light": "secondary"},
            "success": {"dark": "secondary", "light": "secondary"},
        },
    }
    return json.dumps(data, indent=2)


def make_starship(t):
    c = THEMES[t]
    lines = [
        "[palettes.colors]",
        f"color1 = '#{c['accent1']}'",
        f"color2 = '#{c['bg']}'",
        f"color3 = '#{c['fg2']}'",
        f"color4 = '#{c['bg2']}'",
        f"color5 = '#{c['bg']}'",
        f"color6 = '#{c['bg1']}'",
        f"color7 = '#{c['bg1']}'",
        f"color8 = '#{c['accent1']}'",
        f"color9 = '#{c['accent3']}'",
        f"color_error = '#{c['error']}'",
    ]
    return "\n".join(lines)


GENERATORS = {
    "hyprland.conf": make_hyprland,
    "ghostty": make_ghostty,
    "waybar.css": make_css,
    "swaync.css": make_css,
    "wlogout.css": make_css,
    "gtk.css": make_gtk_css,
    "rofi.rasi": make_rofi,
    "tmux.conf": make_tmux,
    "opencode.json": make_opencode,
    "starship.toml": make_starship,
}

for theme_name in THEMES:
    theme_dir = os.path.join(THEMES_DIR, theme_name)
    os.makedirs(theme_dir, exist_ok=True)
    for filename, generator in GENERATORS.items():
        content = generator(theme_name)
        path = os.path.join(theme_dir, filename)
        with open(path, "w") as f:
            f.write(content + "\n")
    print(f"Generated: {theme_name}")

# Write current placeholder
current_file = os.path.join(THEMES_DIR, "current")
if not os.path.exists(current_file):
    with open(current_file, "w") as f:
        f.write("gruvbox-dark\n")

print("Done.")
