set -gq @thm_bg                    "#32302f"
set -gq @thm_status_bg             "#282828"
set -gq @thm_active_bg             "#3c3836"
set -gq @thm_fg                    "#d5c4a1"
set -gq @thm_fg_bright             "#ebdbb2"
set -gq @thm_active_fg             "#ebdbb2"
set -gq @thm_accent                "#d79921"
set -gq @thm_border                "#504945"
set -gq @thm_prefix_bg             "#d65d0e"
set -gq @thm_prefix_fg             "#ebdbb2"
set -gq @thm_copy_fg               "#458588"
set -gq @thm_zoom_fg               "#98971a"
