[palettes.colors]
color1 = '#82aaff'
color2 = '#0f111a'
color3 = '#828bb8'
color4 = '#1f2233'
color5 = '#0f111a'
color6 = '#090b10'
color7 = '#090b10'
color8 = '#82aaff'
color9 = '#c792ea'
color_error = '#f07178'
