set -gq @thm_bg                    "#0f111a"
set -gq @thm_status_bg             "#090b10"
set -gq @thm_active_bg             "#1f2233"
set -gq @thm_fg                    "#828bb8"
set -gq @thm_fg_bright             "#a6accd"
set -gq @thm_active_fg             "#a6accd"
set -gq @thm_accent                "#82aaff"
set -gq @thm_border                "#2a2e42"
set -gq @thm_prefix_bg             "#82aaff"
set -gq @thm_prefix_fg             "#a6accd"
set -gq @thm_copy_fg               "#c792ea"
set -gq @thm_zoom_fg               "#89ddff"
