set -gq @thm_bg                    "#19120d"
set -gq @thm_status_bg             "#140d08"
set -gq @thm_active_bg             "#312822"
set -gq @thm_fg                    "#d6c3b7"
set -gq @thm_fg_bright             "#f0dfd6"
set -gq @thm_active_fg             "#f0dfd6"
set -gq @thm_accent                "#ffb783"
set -gq @thm_border                "#52443b"
set -gq @thm_prefix_bg             "#6d390b"
set -gq @thm_prefix_fg             "#ffdcc5"
set -gq @thm_copy_fg               "#c8ca94"
set -gq @thm_zoom_fg               "#e4bfa7"
