set -gq @thm_bg                    "#1a120e"
set -gq @thm_status_bg             "#140c09"
set -gq @thm_active_bg             "#322824"
set -gq @thm_fg                    "#d7c2ba"
set -gq @thm_fg_bright             "#f1dfd8"
set -gq @thm_active_fg             "#f1dfd8"
set -gq @thm_accent                "#ffb694"
set -gq @thm_border                "#52443d"
set -gq @thm_prefix_bg             "#713719"
set -gq @thm_prefix_fg             "#ffdbcc"
set -gq @thm_copy_fg               "#d1c88f"
set -gq @thm_zoom_fg               "#e6bead"
