set -gq @thm_bg                    "#0e1513"
set -gq @thm_status_bg             "#090f0e"
set -gq @thm_active_bg             "#252b29"
set -gq @thm_fg                    "#bec9c5"
set -gq @thm_fg_bright             "#dee4e1"
set -gq @thm_active_fg             "#dee4e1"
set -gq @thm_accent                "#84d6c3"
set -gq @thm_border                "#3f4946"
set -gq @thm_prefix_bg             "#005045"
set -gq @thm_prefix_fg             "#a0f2df"
set -gq @thm_copy_fg               "#abcae4"
set -gq @thm_zoom_fg               "#b1ccc4"
