$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(1f1f28ff)
$bg1        = rgba(16161dff)
$bg2        = rgba(2a2a37ff)
$bg3        = rgba(363646ff)
$bg4        = rgba(54546dff)

# Foregrounds
$fg         = rgba(dcd7baff)
$fg2        = rgba(c8c093ff)
$fg3        = rgba(727169ff)

# Named colors
$red        = rgba(c34043ff)
$orange     = rgba(ffa066ff)
$yellow     = rgba(c0a36eff)
$green      = rgba(76946aff)
$cyan       = rgba(7aa89fff)
$blue       = rgba(7e9cd8ff)
$purple     = rgba(938aa9ff)

# Accents
$accent     = rgba(7e9cd8ff)
$accent2    = rgba(76946aff)
$accent3    = rgba(d27e99ff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
