$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(1f1f28ff)
$on_background          = rgba(dcd7baff)

$primary                = rgba(7e9cd8ff)
$on_primary             = rgba(1f1f28ff)
$primary_container      = rgba(363646ff)
$on_primary_container   = rgba(7e9cd8ff)
$primary_fixed          = rgba(7e9cd8ff)
$primary_fixed_dim      = rgba(7e9cd8ff)
$inverse_primary        = rgba(363646ff)

$secondary              = rgba(76946aff)
$on_secondary           = rgba(1f1f28ff)
$secondary_container    = rgba(2a2a37ff)
$on_secondary_container = rgba(76946aff)
$secondary_fixed        = rgba(76946aff)
$secondary_fixed_dim    = rgba(76946aff)

$tertiary               = rgba(d27e99ff)
$on_tertiary            = rgba(1f1f28ff)
$tertiary_container     = rgba(363646ff)
$on_tertiary_container  = rgba(d27e99ff)
$tertiary_fixed         = rgba(d27e99ff)
$tertiary_fixed_dim     = rgba(d27e99ff)

$error                  = rgba(c34043ff)
$on_error               = rgba(1f1f28ff)
$error_container        = rgba(2a2a37ff)
$on_error_container     = rgba(c34043ff)

$surface                = rgba(16161dff)
$on_surface             = rgba(dcd7baff)
$surface_variant        = rgba(363646ff)
$on_surface_variant     = rgba(c8c093ff)
$surface_bright         = rgba(2a2a37ff)
$surface_dim            = rgba(1f1f28ff)
$surface_tint           = rgba(7e9cd8ff)
$surface_container_lowest  = rgba(16161dff)
$surface_container_low     = rgba(16161dff)
$surface_container         = rgba(2a2a37ff)
$surface_container_high    = rgba(363646ff)
$surface_container_highest = rgba(54546dff)

$inverse_on_surface     = rgba(1f1f28ff)
$inverse_surface        = rgba(dcd7baff)

$outline                = rgba(727169ff)
$outline_variant        = rgba(363646ff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(7e9cd8ff)

# Extended palette vars
$on_primary_fixed            = rgba(1f1f28ff)
$on_primary_fixed_variant    = rgba(363646ff)
$on_secondary_fixed          = rgba(1f1f28ff)
$on_secondary_fixed_variant  = rgba(363646ff)
$on_tertiary_fixed           = rgba(1f1f28ff)
$on_tertiary_fixed_variant   = rgba(363646ff)
