[palettes.colors]
color1 = '#7e9cd8'
color2 = '#1f1f28'
color3 = '#c8c093'
color4 = '#2a2a37'
color5 = '#1f1f28'
color6 = '#16161d'
color7 = '#16161d'
color8 = '#7e9cd8'
color9 = '#d27e99'
color_error = '#c34043'
