set -gq @thm_bg                    "#1f1f28"
set -gq @thm_status_bg             "#16161d"
set -gq @thm_active_bg             "#2a2a37"
set -gq @thm_fg                    "#c8c093"
set -gq @thm_fg_bright             "#dcd7ba"
set -gq @thm_active_fg             "#dcd7ba"
set -gq @thm_accent                "#7e9cd8"
set -gq @thm_border                "#363646"
set -gq @thm_prefix_bg             "#7e9cd8"
set -gq @thm_prefix_fg             "#dcd7ba"
set -gq @thm_copy_fg               "#d27e99"
set -gq @thm_zoom_fg               "#76946a"
