$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(232136ff)
$bg1        = rgba(1f1d2eff)
$bg2        = rgba(2a273fff)
$bg3        = rgba(393552ff)
$bg4        = rgba(6e6a86ff)

# Foregrounds
$fg         = rgba(e0def4ff)
$fg2        = rgba(908caaff)
$fg3        = rgba(6e6a86ff)

# Named colors
$red        = rgba(eb6f92ff)
$orange     = rgba(f6c177ff)
$yellow     = rgba(f6c177ff)
$green      = rgba(3e8fb0ff)
$cyan       = rgba(9ccfd8ff)
$blue       = rgba(3e8fb0ff)
$purple     = rgba(c4a7e7ff)

# Accents
$accent     = rgba(c4a7e7ff)
$accent2    = rgba(9ccfd8ff)
$accent3    = rgba(ea9a97ff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
