[palettes.colors]
color1 = '#c4a7e7'
color2 = '#232136'
color3 = '#908caa'
color4 = '#2a273f'
color5 = '#232136'
color6 = '#1f1d2e'
color7 = '#1f1d2e'
color8 = '#c4a7e7'
color9 = '#ea9a97'
color_error = '#eb6f92'
