$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(1d2021ff)
$on_background          = rgba(ebdbb2ff)

$primary                = rgba(fabd2fff)
$on_primary             = rgba(1d2021ff)
$primary_container      = rgba(3c3836ff)
$on_primary_container   = rgba(fabd2fff)
$primary_fixed          = rgba(fabd2fff)
$primary_fixed_dim      = rgba(fabd2fff)
$inverse_primary        = rgba(3c3836ff)

$secondary              = rgba(b8bb26ff)
$on_secondary           = rgba(1d2021ff)
$secondary_container    = rgba(282828ff)
$on_secondary_container = rgba(b8bb26ff)
$secondary_fixed        = rgba(b8bb26ff)
$secondary_fixed_dim    = rgba(b8bb26ff)

$tertiary               = rgba(83a598ff)
$on_tertiary            = rgba(1d2021ff)
$tertiary_container     = rgba(3c3836ff)
$on_tertiary_container  = rgba(83a598ff)
$tertiary_fixed         = rgba(83a598ff)
$tertiary_fixed_dim     = rgba(83a598ff)

$error                  = rgba(fb4934ff)
$on_error               = rgba(1d2021ff)
$error_container        = rgba(282828ff)
$on_error_container     = rgba(fb4934ff)

$surface                = rgba(1b1b1bff)
$on_surface             = rgba(ebdbb2ff)
$surface_variant        = rgba(3c3836ff)
$on_surface_variant     = rgba(d5c4a1ff)
$surface_bright         = rgba(282828ff)
$surface_dim            = rgba(1d2021ff)
$surface_tint           = rgba(fabd2fff)
$surface_container_lowest  = rgba(1b1b1bff)
$surface_container_low     = rgba(1b1b1bff)
$surface_container         = rgba(282828ff)
$surface_container_high    = rgba(3c3836ff)
$surface_container_highest = rgba(504945ff)

$inverse_on_surface     = rgba(1d2021ff)
$inverse_surface        = rgba(ebdbb2ff)

$outline                = rgba(a89984ff)
$outline_variant        = rgba(3c3836ff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(fe8019ff)

# Extended palette vars
$on_primary_fixed            = rgba(1d2021ff)
$on_primary_fixed_variant    = rgba(3c3836ff)
$on_secondary_fixed          = rgba(1d2021ff)
$on_secondary_fixed_variant  = rgba(3c3836ff)
$on_tertiary_fixed           = rgba(1d2021ff)
$on_tertiary_fixed_variant   = rgba(3c3836ff)
