$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(1d2021ff)
$bg1        = rgba(1b1b1bff)
$bg2        = rgba(282828ff)
$bg3        = rgba(3c3836ff)
$bg4        = rgba(504945ff)

# Foregrounds
$fg         = rgba(ebdbb2ff)
$fg2        = rgba(d5c4a1ff)
$fg3        = rgba(a89984ff)

# Named colors
$red        = rgba(fb4934ff)
$orange     = rgba(fe8019ff)
$yellow     = rgba(fabd2fff)
$green      = rgba(b8bb26ff)
$cyan       = rgba(8ec07cff)
$blue       = rgba(83a598ff)
$purple     = rgba(d3869bff)

# Accents
$accent     = rgba(fabd2fff)
$accent2    = rgba(b8bb26ff)
$accent3    = rgba(83a598ff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
