[palettes.colors]
color1 = '#fabd2f'
color2 = '#1d2021'
color3 = '#d5c4a1'
color4 = '#282828'
color5 = '#1d2021'
color6 = '#1b1b1b'
color7 = '#1b1b1b'
color8 = '#fabd2f'
color9 = '#83a598'
color_error = '#fb4934'
