set -gq @thm_bg                    "#1d2021"
set -gq @thm_status_bg             "#1b1b1b"
set -gq @thm_active_bg             "#282828"
set -gq @thm_fg                    "#d5c4a1"
set -gq @thm_fg_bright             "#ebdbb2"
set -gq @thm_active_fg             "#ebdbb2"
set -gq @thm_accent                "#fabd2f"
set -gq @thm_border                "#3c3836"
set -gq @thm_prefix_bg             "#fe8019"
set -gq @thm_prefix_fg             "#ebdbb2"
set -gq @thm_copy_fg               "#83a598"
set -gq @thm_zoom_fg               "#b8bb26"
