$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(1d1f21ff)
$bg1        = rgba(161719ff)
$bg2        = rgba(282a2eff)
$bg3        = rgba(373b41ff)
$bg4        = rgba(4b5056ff)

# Foregrounds
$fg         = rgba(c5c8c6ff)
$fg2        = rgba(b4b7b4ff)
$fg3        = rgba(969896ff)

# Named colors
$red        = rgba(cc6666ff)
$orange     = rgba(de935fff)
$yellow     = rgba(f0c674ff)
$green      = rgba(b5bd68ff)
$cyan       = rgba(8abeb7ff)
$blue       = rgba(81a2beff)
$purple     = rgba(b294bbff)

# Accents
$accent     = rgba(81a2beff)
$accent2    = rgba(8abeb7ff)
$accent3    = rgba(b294bbff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
