$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(1d1f21ff)
$on_background          = rgba(c5c8c6ff)

$primary                = rgba(81a2beff)
$on_primary             = rgba(1d1f21ff)
$primary_container      = rgba(373b41ff)
$on_primary_container   = rgba(81a2beff)
$primary_fixed          = rgba(81a2beff)
$primary_fixed_dim      = rgba(81a2beff)
$inverse_primary        = rgba(373b41ff)

$secondary              = rgba(8abeb7ff)
$on_secondary           = rgba(1d1f21ff)
$secondary_container    = rgba(282a2eff)
$on_secondary_container = rgba(8abeb7ff)
$secondary_fixed        = rgba(8abeb7ff)
$secondary_fixed_dim    = rgba(8abeb7ff)

$tertiary               = rgba(b294bbff)
$on_tertiary            = rgba(1d1f21ff)
$tertiary_container     = rgba(373b41ff)
$on_tertiary_container  = rgba(b294bbff)
$tertiary_fixed         = rgba(b294bbff)
$tertiary_fixed_dim     = rgba(b294bbff)

$error                  = rgba(cc6666ff)
$on_error               = rgba(1d1f21ff)
$error_container        = rgba(282a2eff)
$on_error_container     = rgba(cc6666ff)

$surface                = rgba(161719ff)
$on_surface             = rgba(c5c8c6ff)
$surface_variant        = rgba(373b41ff)
$on_surface_variant     = rgba(b4b7b4ff)
$surface_bright         = rgba(282a2eff)
$surface_dim            = rgba(1d1f21ff)
$surface_tint           = rgba(81a2beff)
$surface_container_lowest  = rgba(161719ff)
$surface_container_low     = rgba(161719ff)
$surface_container         = rgba(282a2eff)
$surface_container_high    = rgba(373b41ff)
$surface_container_highest = rgba(4b5056ff)

$inverse_on_surface     = rgba(1d1f21ff)
$inverse_surface        = rgba(c5c8c6ff)

$outline                = rgba(969896ff)
$outline_variant        = rgba(373b41ff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(81a2beff)

# Extended palette vars
$on_primary_fixed            = rgba(1d1f21ff)
$on_primary_fixed_variant    = rgba(373b41ff)
$on_secondary_fixed          = rgba(1d1f21ff)
$on_secondary_fixed_variant  = rgba(373b41ff)
$on_tertiary_fixed           = rgba(1d1f21ff)
$on_tertiary_fixed_variant   = rgba(373b41ff)
