set -gq @thm_bg                    "#1d1f21"
set -gq @thm_status_bg             "#161719"
set -gq @thm_active_bg             "#282a2e"
set -gq @thm_fg                    "#b4b7b4"
set -gq @thm_fg_bright             "#c5c8c6"
set -gq @thm_active_fg             "#c5c8c6"
set -gq @thm_accent                "#81a2be"
set -gq @thm_border                "#373b41"
set -gq @thm_prefix_bg             "#de935f"
set -gq @thm_prefix_fg             "#c5c8c6"
set -gq @thm_copy_fg               "#b294bb"
set -gq @thm_zoom_fg               "#8abeb7"
