$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(192330ff)
$on_background          = rgba(cdcecfff)

$primary                = rgba(82aaffff)
$on_primary             = rgba(192330ff)
$primary_container      = rgba(29394fff)
$on_primary_container   = rgba(82aaffff)
$primary_fixed          = rgba(82aaffff)
$primary_fixed_dim      = rgba(82aaffff)
$inverse_primary        = rgba(29394fff)

$secondary              = rgba(86e1fcff)
$on_secondary           = rgba(192330ff)
$secondary_container    = rgba(212e3fff)
$on_secondary_container = rgba(86e1fcff)
$secondary_fixed        = rgba(86e1fcff)
$secondary_fixed_dim    = rgba(86e1fcff)

$tertiary               = rgba(c099ffff)
$on_tertiary            = rgba(192330ff)
$tertiary_container     = rgba(29394fff)
$on_tertiary_container  = rgba(c099ffff)
$tertiary_fixed         = rgba(c099ffff)
$tertiary_fixed_dim     = rgba(c099ffff)

$error                  = rgba(c94f6dff)
$on_error               = rgba(192330ff)
$error_container        = rgba(212e3fff)
$on_error_container     = rgba(c94f6dff)

$surface                = rgba(131a24ff)
$on_surface             = rgba(cdcecfff)
$surface_variant        = rgba(29394fff)
$on_surface_variant     = rgba(738091ff)
$surface_bright         = rgba(212e3fff)
$surface_dim            = rgba(192330ff)
$surface_tint           = rgba(82aaffff)
$surface_container_lowest  = rgba(131a24ff)
$surface_container_low     = rgba(131a24ff)
$surface_container         = rgba(212e3fff)
$surface_container_high    = rgba(29394fff)
$surface_container_highest = rgba(39506dff)

$inverse_on_surface     = rgba(192330ff)
$inverse_surface        = rgba(cdcecfff)

$outline                = rgba(526175ff)
$outline_variant        = rgba(29394fff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(82aaffff)

# Extended palette vars
$on_primary_fixed            = rgba(192330ff)
$on_primary_fixed_variant    = rgba(29394fff)
$on_secondary_fixed          = rgba(192330ff)
$on_secondary_fixed_variant  = rgba(29394fff)
$on_tertiary_fixed           = rgba(192330ff)
$on_tertiary_fixed_variant   = rgba(29394fff)
