$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(192330ff)
$bg1        = rgba(131a24ff)
$bg2        = rgba(212e3fff)
$bg3        = rgba(29394fff)
$bg4        = rgba(39506dff)

# Foregrounds
$fg         = rgba(cdcecfff)
$fg2        = rgba(738091ff)
$fg3        = rgba(526175ff)

# Named colors
$red        = rgba(c94f6dff)
$orange     = rgba(f4a261ff)
$yellow     = rgba(d9bc8cff)
$green      = rgba(81b29aff)
$cyan       = rgba(86e1fcff)
$blue       = rgba(82aaffff)
$purple     = rgba(c099ffff)

# Accents
$accent     = rgba(82aaffff)
$accent2    = rgba(86e1fcff)
$accent3    = rgba(c099ffff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
