[palettes.colors]
color1 = '#82aaff'
color2 = '#192330'
color3 = '#738091'
color4 = '#212e3f'
color5 = '#192330'
color6 = '#131a24'
color7 = '#131a24'
color8 = '#82aaff'
color9 = '#c099ff'
color_error = '#c94f6d'
