set -gq @thm_bg                    "#192330"
set -gq @thm_status_bg             "#131a24"
set -gq @thm_active_bg             "#212e3f"
set -gq @thm_fg                    "#738091"
set -gq @thm_fg_bright             "#cdcecf"
set -gq @thm_active_fg             "#cdcecf"
set -gq @thm_accent                "#82aaff"
set -gq @thm_border                "#29394f"
set -gq @thm_prefix_bg             "#f4a261"
set -gq @thm_prefix_fg             "#cdcecf"
set -gq @thm_copy_fg               "#c099ff"
set -gq @thm_zoom_fg               "#86e1fc"
