$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(191724ff)
$bg1        = rgba(1f1d2eff)
$bg2        = rgba(26233aff)
$bg3        = rgba(6e6a86ff)
$bg4        = rgba(9893a5ff)

# Foregrounds
$fg         = rgba(e0def4ff)
$fg2        = rgba(908caaff)
$fg3        = rgba(6e6a86ff)

# Named colors
$red        = rgba(eb6f92ff)
$orange     = rgba(f6c177ff)
$yellow     = rgba(ebbcbaff)
$green      = rgba(31748fff)
$cyan       = rgba(9ccfd8ff)
$blue       = rgba(31748fff)
$purple     = rgba(c4a7e7ff)

# Accents
$accent     = rgba(f6c177ff)
$accent2    = rgba(9ccfd8ff)
$accent3    = rgba(c4a7e7ff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
