[palettes.colors]
color1 = '#f6c177'
color2 = '#191724'
color3 = '#908caa'
color4 = '#26233a'
color5 = '#191724'
color6 = '#1f1d2e'
color7 = '#1f1d2e'
color8 = '#f6c177'
color9 = '#c4a7e7'
color_error = '#eb6f92'
