set -gq @thm_bg                    "#191724"
set -gq @thm_status_bg             "#1f1d2e"
set -gq @thm_active_bg             "#26233a"
set -gq @thm_fg                    "#908caa"
set -gq @thm_fg_bright             "#e0def4"
set -gq @thm_active_fg             "#e0def4"
set -gq @thm_accent                "#f6c177"
set -gq @thm_border                "#6e6a86"
set -gq @thm_prefix_bg             "#f6c177"
set -gq @thm_prefix_fg             "#e0def4"
set -gq @thm_copy_fg               "#c4a7e7"
set -gq @thm_zoom_fg               "#9ccfd8"
