$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(1b1e28ff)
$on_background          = rgba(e4f0fbff)

$primary                = rgba(89ddffff)
$on_primary             = rgba(1b1e28ff)
$primary_container      = rgba(4b5263ff)
$on_primary_container   = rgba(89ddffff)
$primary_fixed          = rgba(89ddffff)
$primary_fixed_dim      = rgba(89ddffff)
$inverse_primary        = rgba(4b5263ff)

$secondary              = rgba(5de4c7ff)
$on_secondary           = rgba(1b1e28ff)
$secondary_container    = rgba(303340ff)
$on_secondary_container = rgba(5de4c7ff)
$secondary_fixed        = rgba(5de4c7ff)
$secondary_fixed_dim    = rgba(5de4c7ff)

$tertiary               = rgba(fcc5e9ff)
$on_tertiary            = rgba(1b1e28ff)
$tertiary_container     = rgba(4b5263ff)
$on_tertiary_container  = rgba(fcc5e9ff)
$tertiary_fixed         = rgba(fcc5e9ff)
$tertiary_fixed_dim     = rgba(fcc5e9ff)

$error                  = rgba(d0679dff)
$on_error               = rgba(1b1e28ff)
$error_container        = rgba(303340ff)
$on_error_container     = rgba(d0679dff)

$surface                = rgba(171922ff)
$on_surface             = rgba(e4f0fbff)
$surface_variant        = rgba(4b5263ff)
$on_surface_variant     = rgba(a6accdff)
$surface_bright         = rgba(303340ff)
$surface_dim            = rgba(1b1e28ff)
$surface_tint           = rgba(89ddffff)
$surface_container_lowest  = rgba(171922ff)
$surface_container_low     = rgba(171922ff)
$surface_container         = rgba(303340ff)
$surface_container_high    = rgba(4b5263ff)
$surface_container_highest = rgba(767c9dff)

$inverse_on_surface     = rgba(1b1e28ff)
$inverse_surface        = rgba(e4f0fbff)

$outline                = rgba(767c9dff)
$outline_variant        = rgba(4b5263ff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(89ddffff)

# Extended palette vars
$on_primary_fixed            = rgba(1b1e28ff)
$on_primary_fixed_variant    = rgba(4b5263ff)
$on_secondary_fixed          = rgba(1b1e28ff)
$on_secondary_fixed_variant  = rgba(4b5263ff)
$on_tertiary_fixed           = rgba(1b1e28ff)
$on_tertiary_fixed_variant   = rgba(4b5263ff)
