$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(1b1e28ff)
$bg1        = rgba(171922ff)
$bg2        = rgba(303340ff)
$bg3        = rgba(4b5263ff)
$bg4        = rgba(767c9dff)

# Foregrounds
$fg         = rgba(e4f0fbff)
$fg2        = rgba(a6accdff)
$fg3        = rgba(767c9dff)

# Named colors
$red        = rgba(d0679dff)
$orange     = rgba(fffac2ff)
$yellow     = rgba(fffac2ff)
$green      = rgba(5de4c7ff)
$cyan       = rgba(89ddffff)
$blue       = rgba(89ddffff)
$purple     = rgba(fcc5e9ff)

# Accents
$accent     = rgba(89ddffff)
$accent2    = rgba(5de4c7ff)
$accent3    = rgba(fcc5e9ff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
