[palettes.colors]
color1 = '#89ddff'
color2 = '#1b1e28'
color3 = '#a6accd'
color4 = '#303340'
color5 = '#1b1e28'
color6 = '#171922'
color7 = '#171922'
color8 = '#89ddff'
color9 = '#fcc5e9'
color_error = '#d0679d'
