set -gq @thm_bg                    "#1b1e28"
set -gq @thm_status_bg             "#171922"
set -gq @thm_active_bg             "#303340"
set -gq @thm_fg                    "#a6accd"
set -gq @thm_fg_bright             "#e4f0fb"
set -gq @thm_active_fg             "#e4f0fb"
set -gq @thm_accent                "#89ddff"
set -gq @thm_border                "#4b5263"
set -gq @thm_prefix_bg             "#89ddff"
set -gq @thm_prefix_fg             "#e4f0fb"
set -gq @thm_copy_fg               "#fcc5e9"
set -gq @thm_zoom_fg               "#5de4c7"
