$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(161616ff)
$bg1        = rgba(0f0f0fff)
$bg2        = rgba(262626ff)
$bg3        = rgba(393939ff)
$bg4        = rgba(525252ff)

# Foregrounds
$fg         = rgba(dde1e6ff)
$fg2        = rgba(a2a9b0ff)
$fg3        = rgba(697077ff)

# Named colors
$red        = rgba(ff7eb6ff)
$orange     = rgba(ffb784ff)
$yellow     = rgba(ffe97bff)
$green      = rgba(42be65ff)
$cyan       = rgba(08bdbaff)
$blue       = rgba(78a9ffff)
$purple     = rgba(be95ffff)

# Accents
$accent     = rgba(78a9ffff)
$accent2    = rgba(08bdbaff)
$accent3    = rgba(be95ffff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
