$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(161616ff)
$on_background          = rgba(dde1e6ff)

$primary                = rgba(78a9ffff)
$on_primary             = rgba(161616ff)
$primary_container      = rgba(393939ff)
$on_primary_container   = rgba(78a9ffff)
$primary_fixed          = rgba(78a9ffff)
$primary_fixed_dim      = rgba(78a9ffff)
$inverse_primary        = rgba(393939ff)

$secondary              = rgba(08bdbaff)
$on_secondary           = rgba(161616ff)
$secondary_container    = rgba(262626ff)
$on_secondary_container = rgba(08bdbaff)
$secondary_fixed        = rgba(08bdbaff)
$secondary_fixed_dim    = rgba(08bdbaff)

$tertiary               = rgba(be95ffff)
$on_tertiary            = rgba(161616ff)
$tertiary_container     = rgba(393939ff)
$on_tertiary_container  = rgba(be95ffff)
$tertiary_fixed         = rgba(be95ffff)
$tertiary_fixed_dim     = rgba(be95ffff)

$error                  = rgba(ff7eb6ff)
$on_error               = rgba(161616ff)
$error_container        = rgba(262626ff)
$on_error_container     = rgba(ff7eb6ff)

$surface                = rgba(0f0f0fff)
$on_surface             = rgba(dde1e6ff)
$surface_variant        = rgba(393939ff)
$on_surface_variant     = rgba(a2a9b0ff)
$surface_bright         = rgba(262626ff)
$surface_dim            = rgba(161616ff)
$surface_tint           = rgba(78a9ffff)
$surface_container_lowest  = rgba(0f0f0fff)
$surface_container_low     = rgba(0f0f0fff)
$surface_container         = rgba(262626ff)
$surface_container_high    = rgba(393939ff)
$surface_container_highest = rgba(525252ff)

$inverse_on_surface     = rgba(161616ff)
$inverse_surface        = rgba(dde1e6ff)

$outline                = rgba(697077ff)
$outline_variant        = rgba(393939ff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(78a9ffff)

# Extended palette vars
$on_primary_fixed            = rgba(161616ff)
$on_primary_fixed_variant    = rgba(393939ff)
$on_secondary_fixed          = rgba(161616ff)
$on_secondary_fixed_variant  = rgba(393939ff)
$on_tertiary_fixed           = rgba(161616ff)
$on_tertiary_fixed_variant   = rgba(393939ff)
