set -gq @thm_bg                    "#161616"
set -gq @thm_status_bg             "#0f0f0f"
set -gq @thm_active_bg             "#262626"
set -gq @thm_fg                    "#a2a9b0"
set -gq @thm_fg_bright             "#dde1e6"
set -gq @thm_active_fg             "#dde1e6"
set -gq @thm_accent                "#78a9ff"
set -gq @thm_border                "#393939"
set -gq @thm_prefix_bg             "#ffb784"
set -gq @thm_prefix_fg             "#dde1e6"
set -gq @thm_copy_fg               "#be95ff"
set -gq @thm_zoom_fg               "#08bdba"
