$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(2d353bff)
$on_background          = rgba(d3c6aaff)

$primary                = rgba(a7c080ff)
$on_primary             = rgba(2d353bff)
$primary_container      = rgba(475258ff)
$on_primary_container   = rgba(a7c080ff)
$primary_fixed          = rgba(a7c080ff)
$primary_fixed_dim      = rgba(a7c080ff)
$inverse_primary        = rgba(475258ff)

$secondary              = rgba(7fbbb3ff)
$on_secondary           = rgba(2d353bff)
$secondary_container    = rgba(3d484dff)
$on_secondary_container = rgba(7fbbb3ff)
$secondary_fixed        = rgba(7fbbb3ff)
$secondary_fixed_dim    = rgba(7fbbb3ff)

$tertiary               = rgba(d699b6ff)
$on_tertiary            = rgba(2d353bff)
$tertiary_container     = rgba(475258ff)
$on_tertiary_container  = rgba(d699b6ff)
$tertiary_fixed         = rgba(d699b6ff)
$tertiary_fixed_dim     = rgba(d699b6ff)

$error                  = rgba(e67e80ff)
$on_error               = rgba(2d353bff)
$error_container        = rgba(3d484dff)
$on_error_container     = rgba(e67e80ff)

$surface                = rgba(272e33ff)
$on_surface             = rgba(d3c6aaff)
$surface_variant        = rgba(475258ff)
$on_surface_variant     = rgba(9da9a0ff)
$surface_bright         = rgba(3d484dff)
$surface_dim            = rgba(2d353bff)
$surface_tint           = rgba(a7c080ff)
$surface_container_lowest  = rgba(272e33ff)
$surface_container_low     = rgba(272e33ff)
$surface_container         = rgba(3d484dff)
$surface_container_high    = rgba(475258ff)
$surface_container_highest = rgba(56635fff)

$inverse_on_surface     = rgba(2d353bff)
$inverse_surface        = rgba(d3c6aaff)

$outline                = rgba(7a8478ff)
$outline_variant        = rgba(475258ff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(a7c080ff)

# Extended palette vars
$on_primary_fixed            = rgba(2d353bff)
$on_primary_fixed_variant    = rgba(475258ff)
$on_secondary_fixed          = rgba(2d353bff)
$on_secondary_fixed_variant  = rgba(475258ff)
$on_tertiary_fixed           = rgba(2d353bff)
$on_tertiary_fixed_variant   = rgba(475258ff)
