[palettes.colors]
color1 = '#a7c080'
color2 = '#2d353b'
color3 = '#9da9a0'
color4 = '#3d484d'
color5 = '#2d353b'
color6 = '#272e33'
color7 = '#272e33'
color8 = '#a7c080'
color9 = '#d699b6'
color_error = '#e67e80'
