set -gq @thm_bg                    "#2d353b"
set -gq @thm_status_bg             "#272e33"
set -gq @thm_active_bg             "#3d484d"
set -gq @thm_fg                    "#9da9a0"
set -gq @thm_fg_bright             "#d3c6aa"
set -gq @thm_active_fg             "#d3c6aa"
set -gq @thm_accent                "#a7c080"
set -gq @thm_border                "#475258"
set -gq @thm_prefix_bg             "#a7c080"
set -gq @thm_prefix_fg             "#d3c6aa"
set -gq @thm_copy_fg               "#d699b6"
set -gq @thm_zoom_fg               "#7fbbb3"
