$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(0f1419ff)
$on_background          = rgba(bfbdb6ff)

$primary                = rgba(39bae6ff)
$on_primary             = rgba(0f1419ff)
$primary_container      = rgba(253340ff)
$on_primary_container   = rgba(39bae6ff)
$primary_fixed          = rgba(39bae6ff)
$primary_fixed_dim      = rgba(39bae6ff)
$inverse_primary        = rgba(253340ff)

$secondary              = rgba(95e6cbff)
$on_secondary           = rgba(0f1419ff)
$secondary_container    = rgba(1b2733ff)
$on_secondary_container = rgba(95e6cbff)
$secondary_fixed        = rgba(95e6cbff)
$secondary_fixed_dim    = rgba(95e6cbff)

$tertiary               = rgba(d2a6ffff)
$on_tertiary            = rgba(0f1419ff)
$tertiary_container     = rgba(253340ff)
$on_tertiary_container  = rgba(d2a6ffff)
$tertiary_fixed         = rgba(d2a6ffff)
$tertiary_fixed_dim     = rgba(d2a6ffff)

$error                  = rgba(f07178ff)
$on_error               = rgba(0f1419ff)
$error_container        = rgba(1b2733ff)
$on_error_container     = rgba(f07178ff)

$surface                = rgba(0b0e14ff)
$on_surface             = rgba(bfbdb6ff)
$surface_variant        = rgba(253340ff)
$on_surface_variant     = rgba(98958eff)
$surface_bright         = rgba(1b2733ff)
$surface_dim            = rgba(0f1419ff)
$surface_tint           = rgba(39bae6ff)
$surface_container_lowest  = rgba(0b0e14ff)
$surface_container_low     = rgba(0b0e14ff)
$surface_container         = rgba(1b2733ff)
$surface_container_high    = rgba(253340ff)
$surface_container_highest = rgba(364a5eff)

$inverse_on_surface     = rgba(0f1419ff)
$inverse_surface        = rgba(bfbdb6ff)

$outline                = rgba(6c7380ff)
$outline_variant        = rgba(253340ff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(39bae6ff)

# Extended palette vars
$on_primary_fixed            = rgba(0f1419ff)
$on_primary_fixed_variant    = rgba(253340ff)
$on_secondary_fixed          = rgba(0f1419ff)
$on_secondary_fixed_variant  = rgba(253340ff)
$on_tertiary_fixed           = rgba(0f1419ff)
$on_tertiary_fixed_variant   = rgba(253340ff)
