$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(0f1419ff)
$bg1        = rgba(0b0e14ff)
$bg2        = rgba(1b2733ff)
$bg3        = rgba(253340ff)
$bg4        = rgba(364a5eff)

# Foregrounds
$fg         = rgba(bfbdb6ff)
$fg2        = rgba(98958eff)
$fg3        = rgba(6c7380ff)

# Named colors
$red        = rgba(f07178ff)
$orange     = rgba(ffb454ff)
$yellow     = rgba(e6b450ff)
$green      = rgba(7fd962ff)
$cyan       = rgba(39bae6ff)
$blue       = rgba(59c2ffff)
$purple     = rgba(d2a6ffff)

# Accents
$accent     = rgba(39bae6ff)
$accent2    = rgba(95e6cbff)
$accent3    = rgba(d2a6ffff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
