[palettes.colors]
color1 = '#39bae6'
color2 = '#0f1419'
color3 = '#98958e'
color4 = '#1b2733'
color5 = '#0f1419'
color6 = '#0b0e14'
color7 = '#0b0e14'
color8 = '#39bae6'
color9 = '#d2a6ff'
color_error = '#f07178'
