set -gq @thm_bg                    "#0f1419"
set -gq @thm_status_bg             "#0b0e14"
set -gq @thm_active_bg             "#1b2733"
set -gq @thm_fg                    "#98958e"
set -gq @thm_fg_bright             "#bfbdb6"
set -gq @thm_active_fg             "#bfbdb6"
set -gq @thm_accent                "#39bae6"
set -gq @thm_border                "#253340"
set -gq @thm_prefix_bg             "#39bae6"
set -gq @thm_prefix_fg             "#bfbdb6"
set -gq @thm_copy_fg               "#d2a6ff"
set -gq @thm_zoom_fg               "#95e6cb"
