[mgr]
cwd = { fg = "#cdd6f4" }
find_keyword = { fg = "#f38ba8", bold = true, italic = true, underline = true }
find_position = { fg = "#f38ba8", bold = true, italic = true }
marker_copied = { fg = "#cba6f7", bg = "#cba6f7" }
marker_cut = { fg = "#89b4fa", bg = "#89b4fa" }
marker_marked = { fg = "#f38ba8", bg = "#f38ba8" }
marker_selected = { fg = "#b4befe", bg = "#b4befe" }
count_copied = { fg = "#1e1e2e", bg = "#cba6f7" }
count_cut = { fg = "#1e1e2e", bg = "#89b4fa" }
count_selected = { fg = "#1e1e2e", bg = "#b4befe" }
border_symbol = "│"
border_style = { fg = "#b4befe" }

[tabs]
active = { fg = "#b4befe", bold = true, bg = "#181825" }
inactive = { fg = "#bac2de", bg = "#181825" }
sep_inner = { open = "[", close = "]" }

[mode]
normal_main = { bg = "#b4befe", fg = "#1e1e2e", bold = true }
normal_alt = { bg = "#45475a", fg = "#bac2de" }
select_main = { bg = "#89b4fa", fg = "#1e1e2e", bold = true }
select_alt = { bg = "#45475a", fg = "#bac2de" }
unset_main = { bg = "#cba6f7", fg = "#1e1e2e", bold = true }
unset_alt = { bg = "#45475a", fg = "#bac2de" }

[status]
perm_type = { fg = "#a6adc8" }
perm_write = { fg = "#cba6f7" }
perm_read = { fg = "#f38ba8" }
perm_exec = { fg = "#89b4fa" }
perm_sep = { fg = "#585b70" }
progress_label = { bold = true }
progress_normal = { fg = "#b4befe", bg = "#313244" }
progress_error = { fg = "#f38ba8", bg = "#313244" }

[which]
cols = 3
mask = { bg = "#313244" }
cand = { fg = "#b4befe" }
rest = { fg = "#bac2de" }
desc = { fg = "#cdd6f4" }
separator = " ▶ "
separator_style = { fg = "#bac2de" }

[pick]
border = { fg = "#b4befe" }
active = { fg = "#cba6f7", bold = true }
inactive = {}

[input]
border = { fg = "#b4befe" }
value = { fg = "#cdd6f4" }

[filetype]
rules = [
  { url = "*", is = "orphan", bg = "#f38ba8" },
  { url = "*", is = "exec", fg = "#fab387" },
  { url = "*", fg = "#cdd6f4" },
  { url = "*/", fg = "#b4befe" },
]
