[palettes.colors]
color1 = '#61afef'
color2 = '#1a212e'
color3 = '#7f848e'
color4 = '#2c313c'
color5 = '#1a212e'
color6 = '#141922'
color7 = '#141922'
color8 = '#61afef'
color9 = '#c678dd'
color_error = '#e06c75'
