[palettes.colors]
color1 = '#61afef'
color2 = '#282c34'
color3 = '#828997'
color4 = '#3e4451'
color5 = '#282c34'
color6 = '#21252b'
color7 = '#21252b'
color8 = '#61afef'
color9 = '#c678dd'
color_error = '#e06c75'
