set -gq @thm_bg                    "#1a212e"
set -gq @thm_status_bg             "#141922"
set -gq @thm_active_bg             "#2c313c"
set -gq @thm_fg                    "#7f848e"
set -gq @thm_fg_bright             "#abb2bf"
set -gq @thm_active_fg             "#abb2bf"
set -gq @thm_accent                "#61afef"
set -gq @thm_border                "#3b4048"
set -gq @thm_prefix_bg             "#61afef"
set -gq @thm_prefix_fg             "#abb2bf"
set -gq @thm_copy_fg               "#c678dd"
set -gq @thm_zoom_fg               "#56b6c2"
