set -gq @thm_bg                    "#282c34"
set -gq @thm_status_bg             "#21252b"
set -gq @thm_active_bg             "#3e4451"
set -gq @thm_fg                    "#828997"
set -gq @thm_fg_bright             "#abb2bf"
set -gq @thm_active_fg             "#abb2bf"
set -gq @thm_accent                "#61afef"
set -gq @thm_border                "#545862"
set -gq @thm_prefix_bg             "#61afef"
set -gq @thm_prefix_fg             "#abb2bf"
set -gq @thm_copy_fg               "#c678dd"
set -gq @thm_zoom_fg               "#56b6c2"
