$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(292522ff)
$on_background          = rgba(ece1d7ff)

$primary                = rgba(a98a78ff)
$on_primary             = rgba(292522ff)
$primary_container      = rgba(4a443eff)
$on_primary_container   = rgba(a98a78ff)
$primary_fixed          = rgba(a98a78ff)
$primary_fixed_dim      = rgba(a98a78ff)
$inverse_primary        = rgba(4a443eff)

$secondary              = rgba(78997aff)
$on_secondary           = rgba(292522ff)
$secondary_container    = rgba(34302cff)
$on_secondary_container = rgba(78997aff)
$secondary_fixed        = rgba(78997aff)
$secondary_fixed_dim    = rgba(78997aff)

$tertiary               = rgba(7b91b2ff)
$on_tertiary            = rgba(292522ff)
$tertiary_container     = rgba(4a443eff)
$on_tertiary_container  = rgba(7b91b2ff)
$tertiary_fixed         = rgba(7b91b2ff)
$tertiary_fixed_dim     = rgba(7b91b2ff)

$error                  = rgba(d47766ff)
$on_error               = rgba(292522ff)
$error_container        = rgba(34302cff)
$on_error_container     = rgba(d47766ff)

$surface                = rgba(1f1b18ff)
$on_surface             = rgba(ece1d7ff)
$surface_variant        = rgba(4a443eff)
$on_surface_variant     = rgba(c1a78eff)
$surface_bright         = rgba(34302cff)
$surface_dim            = rgba(292522ff)
$surface_tint           = rgba(a98a78ff)
$surface_container_lowest  = rgba(1f1b18ff)
$surface_container_low     = rgba(1f1b18ff)
$surface_container         = rgba(34302cff)
$surface_container_high    = rgba(4a443eff)
$surface_container_highest = rgba(5a524cff)

$inverse_on_surface     = rgba(292522ff)
$inverse_surface        = rgba(ece1d7ff)

$outline                = rgba(867462ff)
$outline_variant        = rgba(4a443eff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(7b91b2ff)

# Extended palette vars
$on_primary_fixed            = rgba(292522ff)
$on_primary_fixed_variant    = rgba(4a443eff)
$on_secondary_fixed          = rgba(292522ff)
$on_secondary_fixed_variant  = rgba(4a443eff)
$on_tertiary_fixed           = rgba(292522ff)
$on_tertiary_fixed_variant   = rgba(4a443eff)
