$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(292522ff)
$bg1        = rgba(1f1b18ff)
$bg2        = rgba(34302cff)
$bg3        = rgba(4a443eff)
$bg4        = rgba(5a524cff)

# Foregrounds
$fg         = rgba(ece1d7ff)
$fg2        = rgba(c1a78eff)
$fg3        = rgba(867462ff)

# Named colors
$red        = rgba(d47766ff)
$orange     = rgba(e49b5dff)
$yellow     = rgba(ebb74aff)
$green      = rgba(78997aff)
$cyan       = rgba(7b91b2ff)
$blue       = rgba(7b91b2ff)
$purple     = rgba(b5a0d2ff)

# Accents
$accent     = rgba(a98a78ff)
$accent2    = rgba(78997aff)
$accent3    = rgba(7b91b2ff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
