set -gq @thm_bg                    "#292522"
set -gq @thm_status_bg             "#1f1b18"
set -gq @thm_active_bg             "#34302c"
set -gq @thm_fg                    "#c1a78e"
set -gq @thm_fg_bright             "#ece1d7"
set -gq @thm_active_fg             "#ece1d7"
set -gq @thm_accent                "#a98a78"
set -gq @thm_border                "#4a443e"
set -gq @thm_prefix_bg             "#e49b5d"
set -gq @thm_prefix_fg             "#ece1d7"
set -gq @thm_copy_fg               "#7b91b2"
set -gq @thm_zoom_fg               "#78997a"
