add_newline = false

format = """$all$directory$git_branch${custom.git_status_dirty}$git_status$cmd_duration$status$character"""

right_format = ""

command_timeout = 2000

palette = 'colors'

[palettes.colors]
color1 = '#81a2be'
color2 = '#1d1f21'
color3 = '#b4b7b4'
color4 = '#282a2e'
color5 = '#1d1f21'
color6 = '#161719'
color7 = '#161719'
color8 = '#81a2be'
color9 = '#b294bb'
color_error = '#cc6666'

[character]
success_symbol = "[❱](color9)"
error_symbol = "[❱](color_error)"
vicmd_symbol = "[❰](color9)"

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'color3'

[directory]
style = "color1"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

[git_branch]
format = '[$branch]($style)'
style = 'bold color8'

[git_status]
format = "[($ahead_behind$stashed)]($style) "
style = "color9"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "•"
style = "color3"
format = "[$symbol]($style)"
shell = ["zsh", "--no-rcs", "--no-globalrcs"]

[cmd_duration]
format = '[$duration]($style) '

[line_break]
disabled = true

[status]
disabled = false
pipestatus = true
format = '[$symbol$int]($style)'
symbol = '✘'
pipestatus_format = '\[$pipestatus\]($style)'
