$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(1e1e2eff)
$bg1        = rgba(181825ff)
$bg2        = rgba(313244ff)
$bg3        = rgba(45475aff)
$bg4        = rgba(585b70ff)

# Foregrounds
$fg         = rgba(cdd6f4ff)
$fg2        = rgba(bac2deff)
$fg3        = rgba(a6adc8ff)

# Named colors
$red        = rgba(f38ba8ff)
$orange     = rgba(fab387ff)
$yellow     = rgba(f9e2afff)
$green      = rgba(a6e3a1ff)
$cyan       = rgba(94e2d5ff)
$blue       = rgba(89b4faff)
$purple     = rgba(cba6f7ff)

# Accents
$accent     = rgba(b4befeff)
$accent2    = rgba(89b4faff)
$accent3    = rgba(cba6f7ff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
