[palettes.colors]
color1 = '#b4befe'
color2 = '#1e1e2e'
color3 = '#bac2de'
color4 = '#313244'
color5 = '#1e1e2e'
color6 = '#181825'
color7 = '#181825'
color8 = '#b4befe'
color9 = '#cba6f7'
color_error = '#f38ba8'
