set -gq @thm_bg                    "#1e1e2e"
set -gq @thm_status_bg             "#181825"
set -gq @thm_active_bg             "#313244"
set -gq @thm_fg                    "#bac2de"
set -gq @thm_fg_bright             "#cdd6f4"
set -gq @thm_active_fg             "#cdd6f4"
set -gq @thm_accent                "#b4befe"
set -gq @thm_border                "#45475a"
set -gq @thm_prefix_bg             "#cba6f7"
set -gq @thm_prefix_fg             "#cdd6f4"
set -gq @thm_copy_fg               "#cba6f7"
set -gq @thm_zoom_fg               "#89b4fa"
