$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(303446ff)
$bg1        = rgba(292c3cff)
$bg2        = rgba(414559ff)
$bg3        = rgba(51576dff)
$bg4        = rgba(626880ff)

# Foregrounds
$fg         = rgba(c6d0f5ff)
$fg2        = rgba(b5bfe2ff)
$fg3        = rgba(a5adceff)

# Named colors
$red        = rgba(e78284ff)
$orange     = rgba(ef9f76ff)
$yellow     = rgba(e5c890ff)
$green      = rgba(a6d189ff)
$cyan       = rgba(99d1dbff)
$blue       = rgba(8caaeeff)
$purple     = rgba(ca9ee6ff)

# Accents
$accent     = rgba(8caaeeff)
$accent2    = rgba(99d1dbff)
$accent3    = rgba(ca9ee6ff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
