$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(303446ff)
$on_background          = rgba(c6d0f5ff)

$primary                = rgba(8caaeeff)
$on_primary             = rgba(303446ff)
$primary_container      = rgba(51576dff)
$on_primary_container   = rgba(8caaeeff)
$primary_fixed          = rgba(8caaeeff)
$primary_fixed_dim      = rgba(8caaeeff)
$inverse_primary        = rgba(51576dff)

$secondary              = rgba(99d1dbff)
$on_secondary           = rgba(303446ff)
$secondary_container    = rgba(414559ff)
$on_secondary_container = rgba(99d1dbff)
$secondary_fixed        = rgba(99d1dbff)
$secondary_fixed_dim    = rgba(99d1dbff)

$tertiary               = rgba(ca9ee6ff)
$on_tertiary            = rgba(303446ff)
$tertiary_container     = rgba(51576dff)
$on_tertiary_container  = rgba(ca9ee6ff)
$tertiary_fixed         = rgba(ca9ee6ff)
$tertiary_fixed_dim     = rgba(ca9ee6ff)

$error                  = rgba(e78284ff)
$on_error               = rgba(303446ff)
$error_container        = rgba(414559ff)
$on_error_container     = rgba(e78284ff)

$surface                = rgba(292c3cff)
$on_surface             = rgba(c6d0f5ff)
$surface_variant        = rgba(51576dff)
$on_surface_variant     = rgba(b5bfe2ff)
$surface_bright         = rgba(414559ff)
$surface_dim            = rgba(303446ff)
$surface_tint           = rgba(8caaeeff)
$surface_container_lowest  = rgba(292c3cff)
$surface_container_low     = rgba(292c3cff)
$surface_container         = rgba(414559ff)
$surface_container_high    = rgba(51576dff)
$surface_container_highest = rgba(626880ff)

$inverse_on_surface     = rgba(303446ff)
$inverse_surface        = rgba(c6d0f5ff)

$outline                = rgba(a5adceff)
$outline_variant        = rgba(51576dff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(8caaeeff)

# Extended palette vars
$on_primary_fixed            = rgba(303446ff)
$on_primary_fixed_variant    = rgba(51576dff)
$on_secondary_fixed          = rgba(303446ff)
$on_secondary_fixed_variant  = rgba(51576dff)
$on_tertiary_fixed           = rgba(303446ff)
$on_tertiary_fixed_variant   = rgba(51576dff)
