[palettes.colors]
color1 = '#8caaee'
color2 = '#303446'
color3 = '#b5bfe2'
color4 = '#414559'
color5 = '#303446'
color6 = '#292c3c'
color7 = '#292c3c'
color8 = '#8caaee'
color9 = '#ca9ee6'
color_error = '#e78284'
