set -gq @thm_bg                    "#303446"
set -gq @thm_status_bg             "#292c3c"
set -gq @thm_active_bg             "#414559"
set -gq @thm_fg                    "#b5bfe2"
set -gq @thm_fg_bright             "#c6d0f5"
set -gq @thm_active_fg             "#c6d0f5"
set -gq @thm_accent                "#8caaee"
set -gq @thm_border                "#51576d"
set -gq @thm_prefix_bg             "#8caaee"
set -gq @thm_prefix_fg             "#c6d0f5"
set -gq @thm_copy_fg               "#ca9ee6"
set -gq @thm_zoom_fg               "#99d1db"
