set -gq @thm_bg                    "{{colors.surface.default.hex}}"
set -gq @thm_status_bg             "{{colors.surface_container_lowest.default.hex}}"
set -gq @thm_active_bg             "{{colors.surface_container_high.default.hex}}"
set -gq @thm_fg                    "{{colors.on_surface_variant.default.hex}}"
set -gq @thm_fg_bright             "{{colors.on_surface.default.hex}}"
set -gq @thm_active_fg             "{{colors.on_surface.default.hex}}"
set -gq @thm_accent                "{{colors.primary.default.hex}}"
set -gq @thm_border                "{{colors.outline_variant.default.hex}}"
set -gq @thm_prefix_bg             "{{colors.primary_container.default.hex}}"
set -gq @thm_prefix_fg             "{{colors.on_primary_container.default.hex}}"
set -gq @thm_copy_fg               "{{colors.tertiary.default.hex}}"
set -gq @thm_zoom_fg               "{{colors.secondary.default.hex}}"
