$font       = SF Pro Display
$font_bold  = SF Pro Display Bold
$clock_font = PP Neue Machina Plain Ultrabold

# Backgrounds
$bg         = rgba(1d2021ff)
$bg1        = rgba(282828ff)
$bg2        = rgba(3c3836ff)
$bg3        = rgba(504945ff)
$bg4        = rgba(665c54ff)

# Foregrounds
$fg         = rgba(ebdbb2ff)
$fg2        = rgba(a89984ff)
$fg3        = rgba(928374ff)

# Named colors
$red        = rgba(cc241dff)
$orange     = rgba(d65d0eff)
$yellow     = rgba(d79921ff)
$green      = rgba(689d6aff)
$cyan       = rgba(8ec07cff)
$blue       = rgba(458588ff)
$purple     = rgba(b16286ff)

# Accents
$accent     = rgba(d79921ff)
$accent2    = rgba(98971aff)
$accent3    = rgba(689d6aff)

# Misc
$shadow     = rgba(000000ff)
$scrim      = rgba(000000ff)
