$font                   = SF Pro Display
$font_bold              = SF Pro Display Bold
$clock_font             = PP Neue Machina Plain Ultrabold

$background             = rgba(1d2021ff)
$on_background          = rgba(ebdbb2ff)

$primary                = rgba(d79921ff)
$on_primary             = rgba(1d2021ff)
$primary_container      = rgba(504945ff)
$on_primary_container   = rgba(d79921ff)
$primary_fixed          = rgba(d79921ff)
$primary_fixed_dim      = rgba(d79921ff)
$inverse_primary        = rgba(504945ff)

$secondary              = rgba(98971aff)
$on_secondary           = rgba(1d2021ff)
$secondary_container    = rgba(3c3836ff)
$on_secondary_container = rgba(98971aff)
$secondary_fixed        = rgba(98971aff)
$secondary_fixed_dim    = rgba(98971aff)

$tertiary               = rgba(689d6aff)
$on_tertiary            = rgba(1d2021ff)
$tertiary_container     = rgba(504945ff)
$on_tertiary_container  = rgba(689d6aff)
$tertiary_fixed         = rgba(689d6aff)
$tertiary_fixed_dim     = rgba(689d6aff)

$error                  = rgba(cc241dff)
$on_error               = rgba(1d2021ff)
$error_container        = rgba(3c3836ff)
$on_error_container     = rgba(cc241dff)

$surface                = rgba(282828ff)
$on_surface             = rgba(ebdbb2ff)
$surface_variant        = rgba(504945ff)
$on_surface_variant     = rgba(a89984ff)
$surface_bright         = rgba(3c3836ff)
$surface_dim            = rgba(1d2021ff)
$surface_tint           = rgba(d79921ff)
$surface_container_lowest  = rgba(282828ff)
$surface_container_low     = rgba(282828ff)
$surface_container         = rgba(3c3836ff)
$surface_container_high    = rgba(504945ff)
$surface_container_highest = rgba(665c54ff)

$inverse_on_surface     = rgba(1d2021ff)
$inverse_surface        = rgba(ebdbb2ff)

$outline                = rgba(928374ff)
$outline_variant        = rgba(504945ff)

$scrim                  = rgba(000000ff)
$shadow                 = rgba(000000ff)

$source_color           = rgba(d65d0eff)

# Extended palette vars
$on_primary_fixed            = rgba(1d2021ff)
$on_primary_fixed_variant    = rgba(504945ff)
$on_secondary_fixed          = rgba(1d2021ff)
$on_secondary_fixed_variant  = rgba(504945ff)
$on_tertiary_fixed           = rgba(1d2021ff)
$on_tertiary_fixed_variant   = rgba(504945ff)
