set -gq @thm_bg                    "#0d1117"
set -gq @thm_status_bg             "#010409"
set -gq @thm_active_bg             "#161b22"
set -gq @thm_fg                    "#8b949e"
set -gq @thm_fg_bright             "#c9d1d9"
set -gq @thm_active_fg             "#c9d1d9"
set -gq @thm_accent                "#58a6ff"
set -gq @thm_border                "#21262d"
set -gq @thm_prefix_bg             "#58a6ff"
set -gq @thm_prefix_fg             "#c9d1d9"
set -gq @thm_copy_fg               "#d2a8ff"
set -gq @thm_zoom_fg               "#79c0ff"
